name: 'shelf'
version: '1.0.0'
config-version: 2

profile: 'shelf'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  shelf:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    dimensions:
      +schema: warehouse
      +materialized: table
    facts:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
