shelf:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'shelf_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'shelf_password') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'shelf_db') }}"
      schema: warehouse
      threads: 4
